---
- name: "test endpoint"
  uri:
    url: "http://{{cheese}}.{{cheese_domain_name}}"
  register: result
  until:
    result['status'] | default(0) == 200
  retries: 30
  delay: 5

- name: "test page http://{{cheese}}.{{cheese_domain_name}}"
  uri:
    url: http://{{cheese}}.{{cheese_domain_name}}
    return_content: "yes"
  register: webpage

- debug:
    msg: "Test page body: {{webpage.content}}"

- name: "fail on missing '{{search_for}}' in page"
  fail: msg="missing '{{search_for}}' in page"
  when: "'{{search_for}}' not in webpage.content"
